FROM public.ecr.aws/lambda/python:3.7

# Copiar fuente de Lambda
COPY . .
RUN python -m pip install --upgrade pip

# Instalación de paquetes en packages/
RUN pip install -r ./requirements.txt
CMD ["api.handler"]
