version: '3'

services:
  log-api:
    container_name: log-api
    build: .
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 8000:5000
    volumes:
      - .:/app/log-api
